version: '3.8'

services:
  you2api:
    build: .
    container_name: you2api
    ports:
      - "8080:8080"
    environment:
      - ALLOWED_TOKENS=your_internal_token # You can add multiple tokens separated by comma
      - DS_TOKEN=your_ds_token # Your you.com token
      - PORT=8080
      - ENABLE_PROXY=false
      - PROXY_URL=
      - PROXY_TIMEOUT_MS=5000
      - LOG_LEVEL=info
    restart: unless-stopped

  # If you need to add Prometheus monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - you2api

  # If you need to add Grafana monitoring dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
